build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Telegram Concert Bot"
  org.opencontainers.image.description: "Telegram bot for concert notifications with Home Assistant integration"
  org.opencontainers.image.source: "https://github.com/rdinv/homeassistant-telegram-concert-bot"
  org.opencontainers.image.licenses: "Apache License 2.0"