name: "Telegram Concert Bot"
version: "1.0.9"
slug: "telegram_concert_bot"
description: "Telegram bot for concert notifications with Home Assistant integration"
url: "https://github.com/rdinv/homeassistant-telegram-concert-bot"
arch:
  - aarch64
init: false
startup: application
boot: auto
map:
  - share:rw
options:
  telegram_token: ""
  log_level: "info"
schema:
  telegram_token: "str"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
image: "local/telegram-concert-bot-{arch}"