name: "Telegram Concert Bot"
version: "1.0.0"
slug: "telegram_concert_bot"
description: "Telegram bot for concert notifications with Home Assistant integration"
arch:
  - aarch64
init: false
startup: application
boot: auto
map:
  - share:rw
options:
  telegram_token: ""
  log_level: "info"
schema:
  telegram_token: "str"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"